### ISSUE TITLE
Update dev software to latest?

### ISSUE THREAD

**Issue by langenet** [alexandroidii/cst8333#14]
Current Versions / Latest version
Python 3.8  / 3.0
PostgreSQL 12 / 13.1
Django 2.2.7 / 3.1.4

**Comment by alexandroidii** [comment]
The following has been updated:

Package             Version Latest Type
------------------- ------- ------ -----
astroid             2.3.3   2.4.2  wheel
atomicwrites        1.3.0   1.4.0  wheel
attrs               19.3.0  20.3.0 wheel
autopep8            1.4.4   1.5.4  sdist
colorama            0.4.1   0.4.4  wheel
Django              2.2.7   3.1.4  wheel
django-crispy-forms 1.8.1   1.10.0 wheel
isort               4.3.21  5.6.4  wheel
lazy-object-proxy   1.4.3   1.5.2  wheel
more-itertools      8.0.0   8.6.0  wheel
mysqlclient         1.4.5   2.0.1  wheel
packaging           19.2    20.7   wheel
pip                 19.3.1  20.3.1 wheel
psycopg2            2.8.4   2.8.6  wheel
psycopg2-binary     2.8.4   2.8.6  wheel
py                  1.8.0   1.9.0  wheel
pycodestyle         2.5.0   2.6.0  wheel
pyparsing           2.4.5   2.4.7  wheel
pytest              5.3.1   6.1.2  wheel
pytz                2019.3  2020.4 wheel
setuptools          42.0.1  50.3.2 wheel
six                 1.13.0  1.15.0 wheel
sqlparse            0.3.0   0.4.1  wheel
wcwidth             0.1.7   0.2.5  wheel
wheel               0.33.6  0.36.1 wheel
wrapt               1.11.2  1.12.1 sdist

**Comment by alexandroidii** [comment]
I upgraded to Python 3.8.6 from our 3.8.0 and updated the Django and other pip installed software below.
