### ISSUE TITLE
Is Reviewer in Incident form. How does it get set

### ISSUE THREAD

**Issue by langenet** [alexandroidii/cst8333#45]
As well this code may need to be revisited since the users comes from users.Users custom user model

**Comment by alexandroidii** [comment]
yeah for sure we will need to change this.  I guess we can still have a column for a "Reviewer" but it will be pointing to that users.Users model instead.

An incident should be able to get assigned to a reviewer so they can verify the information before it get's published.  That is a section of the app that is missing still.  Or maybe we turn the search incident into the same place that would go through incidents to pick and choose from.

**Comment by alexandroidii** [comment]
This has been implemented.
