### ISSUE TITLE
Update dropdowns dynamically

### ISSUE THREAD

**Issue by langenet** [alexandroidii/cst8333#7]
To be able to specify an industry type not available in a dropdown selection list

**Comment by alexandroidii** [comment]
Is this list going to be updated by the Admins only? 

Or do we allow end users to add new industries simply by entering new values in that field, saving it to the database and it becomes a new industry others can access.

**Comment by alexandroidii** [comment]
The field should be a searchable drop down where if the item is not in the list, it is considered "Other".  

The list of "Others" can be added to the searchable list once approved by a reviewer.

**Comment by alexandroidii** [comment]
All drop downs have been converted to classes which are stored in the database and updates via the django admin interface.
