### ISSUE TITLE
Review/validation before entry can be viewed by others

### ISSUE THREAD

**Issue by langenet** [alexandroidii/cst8333#8]

**Comment by langenet** [comment]
1)	Admin dashboard for all entries to allow us to edit but more importantly to validate all entries

**Comment by alexandroidii** [comment]
a user has to register first as a separate event and validate their account via email.

Once validated, then they can submit a new incident.

**Comment by alexandroidii** [comment]
After a Scenario is submitted, the is_reviewed flag is set to false so it is not visible to other submitters.  Once a reviewer finishes reviewing it, they use the Publish button to flip the is_reviewed flag to True.
